# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
- push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2022
        - windows-2025
        - macos-14
        - macos-15
        - ubuntu-22.04
        - ubuntu-24.04
      fail-fast: false
    steps:
    - name: Turn off auto-crlf
      run: git config --global core.autocrlf false
    - name: Checkout source codes
      uses: actions/checkout@v6
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: package.json
    - name: Cache NPM
      uses: ./.github/actions/cache-npm
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Exit if differ (forgot to commit dist dir?)
      run: git diff --exit-code --quiet
    - name: Verify
      run: npm run verify
