# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Connection test
jobs:
  ssh:
    name: Connect to github.com on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
        - Windows-latest
        - macOS-latest
        - Ubuntu-latest
      fail-fast: false
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@development
      with:
        private-key: ${{ secrets.SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        name: id_rsa # optional
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # optional
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
