# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Docker container (CentOS)

on:
- push

jobs:
  verify:
    name: Verify
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
        docker_image:
        - quay.io/centos/centos:stream8
    uses: "./.github/workflows/reusable-verify.yml"
    with:
      os: ${{ matrix.os }}
      docker_image: ${{ matrix.docker_image }}
      package_installation_command: yum install -y git openssh-clients
    secrets: inherit
