# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Docker container on Ubuntu 20.04

on:
- push

jobs:
  ssh:
    name: Connect to github.com
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
    - name: Install packages
      run: |
        apt update
        apt -y install openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
