# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Docker container (CentOS)

on:
- push

jobs:
  verify:
    name: Verify
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - ubuntu-22.04
        container:
        - quay.io/centos/centos:centos7
        - quay.io/centos/centos:stream8
    uses: "./.github/workflows/reusable-verify-container.yml"
    with:
      os: ${{ matrix.os }}
      container: ${{ matrix.container }}
      package_installation_command: yum install -y git openssh-clients
    secrets: inherit
