# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Connection test
jobs:
  ssh:
    name: Connect to github.com on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - Windows-latest
        - macOS-latest
        - Ubuntu-latest
      fail-fast: false
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@HEAD
      with:
        private-key: ${{ secrets.SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # optional
    - name: print created files
      run: ls ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-with-name:
    name: Connect to github.com on ${{ matrix.os }} with name
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - Windows-latest
        - macOS-latest
        - Ubuntu-latest
      fail-fast: false
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@HEAD
      with:
        private-key: ${{ secrets.SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # optional
        name: ssh_key_name # optional
        config: | # optional
          Host github
            Hostname github.com
            User git
            IdentityFile ~/.ssh/ssh_key_name
    - name: print created files
      run: ls ~/.ssh
    - name: git clone through SSH
      run: git clone github:shimataro/ssh-key-action.git tmp
  call-multiple-times:
    name: Call this action multiple times on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - Windows-latest
        - macOS-latest
        - Ubuntu-latest
      fail-fast: false
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@feature/append-config-known_hosts
      with:
        private-key: "DUMMY-PRIVATE-KEY"
        public-key: "DUMMY-PUBLIC-KEY"
        known-hosts: |
          DUMMY-KNOWN-HOSTS
        config: |
          DUMMY-CONFIG
    - name: print created files
      run: |
        ls ~/.ssh
        cat ~/.ssh/known_hosts
        cat ~/.ssh/config
    - name: Install SSH key again
      uses: shimataro/ssh-key-action@feature/append-config-known_hosts
      with:
        private-key: "DUMMY-PRIVATE-KEY"
        public-key: "DUMMY-PUBLIC-KEY"
        name: "id_rsa-2"
        known-hosts: |                   # appended
          DUMMY-KNOWN-HOSTS
        config: |                        # appended
          DUMMY-CONFIG
    - name: print created files again
      run: |
        ls ~/.ssh
        cat ~/.ssh/known_hosts
        cat ~/.ssh/config
