# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Docker container

on:
- push

jobs:
  ssh-pem:
    name: Connect to github.com (PEM format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - windows-2019
        - ubuntu-16.04
        - ubuntu-18.04
        - ubuntu-20.04
        container:
        - ubuntu:16.04
        - ubuntu:18.04
        - ubuntu:20.04
      fail-fast: false
    steps:
    - name: Install packages
      run: |
        apt update
        apt -y install openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-pkcs8:
    name: Connect to github.com (PKCS8 format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-16.04
        - ubuntu-18.04
        - ubuntu-20.04
        container:
        - ubuntu:16.04
        - ubuntu:18.04
        - ubuntu:20.04
      fail-fast: false
    steps:
    - name: Install packages
      run: |
        apt update
        apt -y install openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PKCS8 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
  ssh-rfc4716:
    name: Connect to github.com (RFC4716 format)
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        os:
        - ubuntu-16.04
        - ubuntu-18.04
        - ubuntu-20.04
        container:
        - ubuntu:16.04
        - ubuntu:18.04
        - ubuntu:20.04
      fail-fast: false
    steps:
    - name: Install packages
      run: |
        apt update
        apt -y install openssh-client git
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_RFC4716 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l /root/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
