# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: "pull_request"
name: Connection test
jobs:
  ssh:
    name: Connect to github.com
    runs-on: "ubuntu-latest"
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@development
      with:
        private-key: ${{ secrets.SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        name: 'id_rsa' # optional
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # optional
    - name: ls
      run: ls -la ~/.ssh/
    - name: install packages
      run: sudo apt install -y openssh-client
    - name: git clone through SSH
      run: git clone git@github.com:shimataro/ssh-key-action.git tmp
